server:
  port: 8020

spring:
  application:
    name: commun-service

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    urls:
      - name: Customer Service
        url: http://localhost:8090/v3/api-docs
      - name: Order Service
        url: http://localhost:8070/v3/api-docs
      - name: Product Service
        url: http://localhost:8050/v3/api-docs
      - name: Payment Service
        url: http://localhost:8060/v3/api-docs
